# domain/ports.py
from typing import Protocol, Iterable, List, Optional
from domain.models import BaseItem, Occurrence

class Repository(Protocol):
    def upsert(self, item: BaseItem) -> None: ...
    def get(self, item_id: str) -> Optional[BaseItem]: ...
    def delete(self, item_id: str) -> bool: ...
    def list_all(self) -> List[BaseItem]: ...
    def list_by_type(self, item_type: str) -> List[BaseItem]: ...
    def filter(self, where_sql: str, params: Iterable = ()) -> List[BaseItem]: ...

class StatusServicePort(Protocol):
    def is_terminal(self, status_key: str) -> bool: ...
    def display_name(self, status_key: str) -> str: ...

class Notifier(Protocol):
    def notify(self, item: BaseItem, occ: Occurrence, message: str) -> None: ...
